services:
  neo4j:
    image: neo4j:latest
    container_name: mongado-neo4j
    ports:
      - "7474:7474"  # HTTP (browser interface)
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/mongado-dev-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - mongado-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "mongado-dev-password", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: mongado-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - mongado-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  backend:
    build:
      context: ./backend
      target: development
    container_name: mongado-backend-dev
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      # Exclude venv to prevent conflicts
      - /app/venv
    environment:
      - DEBUG=true
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=mongado-dev-password
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_ENABLED=true
    env_file:
      - ./backend/.env
    networks:
      - mongado-network
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_started
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: mongado-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Exclude node_modules to prevent conflicts
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - mongado-network
    restart: unless-stopped

networks:
  mongado-network:
    driver: bridge

volumes:
  neo4j-data:
  neo4j-logs:
  ollama-data:
