"""Pydantic models for API requests and responses."""

from models.admin import (
    BackupCreateResponse,
    BackupInfo,
    BackupListResponse,
    DatabaseHealthResponse,
    FeatureFlagInfo,
    FeatureFlagsResponse,
    FeatureFlagUpdateRequest,
    FeatureFlagUpdateResponse,
    ResourceUsageResponse,
    RestoreRequest,
    RestoreResponse,
    UploadCleanupResponse,
)
from models.ai import (
    BatchConceptExtractionResponse,
    BatchConceptSuggestion,
    ConceptExtractionResponse,
    ConceptSuggestion,
    EditorAssistRequest,
    EditorAssistResponse,
    EmbeddingSyncResponse,
    GPUStatusResponse,
    QuestionRequest,
    QuestionResponse,
    SummaryResponse,
    SynthesisRequest,
    SynthesisResponse,
    WarmupResponse,
)
from models.auth import (
    AuthenticationOptionsResponse,
    AuthenticationVerifyRequest,
    CredentialDeleteResponse,
    CredentialInfo,
    CredentialsListResponse,
    RegistrationOptionsRequest,
    RegistrationOptionsResponse,
    RegistrationVerifyRequest,
    SessionResponse,
    SessionStatusResponse,
)
from models.library import (
    LibraryEntryCreate,
    LibraryEntryUpdate,
    LibraryListResponse,
)
from models.note import (
    BacklinksResponse,
    LinkSuggestion,
    LinkSuggestionsResponse,
    NoteCreate,
    NoteResponse,
    NotesListResponse,
    NoteUpdate,
    TagSuggestion,
    TagSuggestionsResponse,
)
from models.resource import (
    ArticleMetadata,
    ArticleMetadataListResponse,
    HealthResponse,
    ImageUploadResponse,
    ReadyResponse,
    Resource,
    ResourceListResponse,
    ResourceResponse,
    StatusResponse,
)
from models.search import SearchRequest, SearchResponse, SearchResult

__all__ = [
    # Admin models
    "BackupCreateResponse",
    "BackupInfo",
    "BackupListResponse",
    "DatabaseHealthResponse",
    "ResourceUsageResponse",
    "FeatureFlagInfo",
    "FeatureFlagsResponse",
    "FeatureFlagUpdateRequest",
    "FeatureFlagUpdateResponse",
    "RestoreRequest",
    "RestoreResponse",
    "UploadCleanupResponse",
    # AI models
    "BatchConceptExtractionResponse",
    "BatchConceptSuggestion",
    "ConceptExtractionResponse",
    "ConceptSuggestion",
    "EditorAssistRequest",
    "EditorAssistResponse",
    "EmbeddingSyncResponse",
    "GPUStatusResponse",
    "QuestionRequest",
    "QuestionResponse",
    "SummaryResponse",
    "SynthesisRequest",
    "SynthesisResponse",
    "WarmupResponse",
    # Auth models (passkeys)
    "AuthenticationOptionsResponse",
    "AuthenticationVerifyRequest",
    "CredentialDeleteResponse",
    "CredentialInfo",
    "CredentialsListResponse",
    # Library models
    "LibraryEntryCreate",
    "LibraryEntryUpdate",
    "LibraryListResponse",
    "RegistrationOptionsRequest",
    "RegistrationOptionsResponse",
    "RegistrationVerifyRequest",
    "SessionResponse",
    "SessionStatusResponse",
    # Note models
    "BacklinksResponse",
    "LinkSuggestion",
    "LinkSuggestionsResponse",
    "NoteCreate",
    "NoteResponse",
    "NotesListResponse",
    "NoteUpdate",
    "TagSuggestion",
    "TagSuggestionsResponse",
    # Resource models
    "ArticleMetadata",
    "ArticleMetadataListResponse",
    "HealthResponse",
    "ImageUploadResponse",
    "ReadyResponse",
    "Resource",
    "ResourceListResponse",
    "ResourceResponse",
    "StatusResponse",
    # Search models
    "SearchRequest",
    "SearchResponse",
    "SearchResult",
]
