name: Deploy Articles Only

on:
  push:
    branches: [main]
    paths:
      - 'backend/static/articles/**'
      - 'backend/static/assets/**'
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy-static:
    name: Deploy Static Content
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_PRIVATE_KEY }}

      - name: Add DigitalOcean host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy static files
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh $DO_USER@$DO_HOST << 'EOF'
            set -e

            echo "📄 Deploying static content only..."

            # Navigate to project directory
            cd /opt/mongado || { echo "Project directory not found"; exit 1; }

            # Pull latest changes
            echo "🔄 Pulling latest static files from main branch..."
            git fetch origin
            git reset --hard origin/main

            # Set environment variable to enable embedding sync on startup for this deployment
            echo "⚙️  Configuring backend to sync embeddings on startup..."
            cd backend
            if [ ! -f .env.prod ]; then
              touch .env.prod
            fi
            # Add or update SYNC_EMBEDDINGS_ON_STARTUP in .env.prod
            if grep -q "^SYNC_EMBEDDINGS_ON_STARTUP=" .env.prod; then
              sed -i 's/^SYNC_EMBEDDINGS_ON_STARTUP=.*/SYNC_EMBEDDINGS_ON_STARTUP=true/' .env.prod
            else
              echo "SYNC_EMBEDDINGS_ON_STARTUP=true" >> .env.prod
            fi
            cd ..

            # Restart only the backend to pick up new articles
            echo "🔄 Restarting backend to reload articles and sync embeddings..."
            docker restart mongado-backend-prod

            # Wait for backend to be healthy (with retries)
            echo "⏳ Waiting for backend to be healthy..."
            MAX_RETRIES=30
            RETRY_INTERVAL=2
            RETRY_COUNT=0

            while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
              if curl -f http://localhost:8000/health > /dev/null 2>&1; then
                echo "✅ Backend is healthy after $((RETRY_COUNT * RETRY_INTERVAL)) seconds"
                break
              fi

              RETRY_COUNT=$((RETRY_COUNT + 1))
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "⏳ Health check attempt $RETRY_COUNT/$MAX_RETRIES failed, retrying in ${RETRY_INTERVAL}s..."
                sleep $RETRY_INTERVAL
              else
                echo "❌ Backend health check failed after $((MAX_RETRIES * RETRY_INTERVAL)) seconds"
                docker logs --tail 50 mongado-backend-prod
                exit 1
              fi
            done

            # Wait for embeddings to complete (check /ready endpoint)
            echo "⏳ Waiting for embedding sync to complete..."
            READY_RETRIES=60  # Up to 2 minutes for embeddings
            READY_COUNT=0

            while [ $READY_COUNT -lt $READY_RETRIES ]; do
              READY_STATUS=$(curl -s http://localhost:8000/ready | grep -o '"ready":[^,}]*' | cut -d':' -f2)
              if [ "$READY_STATUS" = "true" ]; then
                echo "✅ Embedding sync complete"
                break
              fi

              READY_COUNT=$((READY_COUNT + 1))
              if [ $READY_COUNT -lt $READY_RETRIES ]; then
                sleep 2
              else
                echo "⚠️  Embedding sync did not complete within timeout (will continue in background)"
              fi
            done

            # Reset SYNC_EMBEDDINGS_ON_STARTUP to false for normal operations
            echo "⚙️  Resetting SYNC_EMBEDDINGS_ON_STARTUP to false..."
            cd /opt/mongado/backend
            if grep -q "^SYNC_EMBEDDINGS_ON_STARTUP=" .env.prod; then
              sed -i 's/^SYNC_EMBEDDINGS_ON_STARTUP=.*/SYNC_EMBEDDINGS_ON_STARTUP=false/' .env.prod
            fi

            echo "✅ Static content deployment complete!"
          EOF

      - name: Deployment notification
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Static content deployed successfully!"
          else
            echo "❌ Static content deployment failed!"
          fi

      - name: Verify deployment
        run: |
          echo "🔍 Verifying static content deployment..."
          sleep 3

          # Check backend API
          BACKEND_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://api.mongado.com/ || echo "000")
          if [ "$BACKEND_STATUS" = "200" ]; then
            echo "✅ Backend API responding (Status: $BACKEND_STATUS)"
          else
            echo "⚠️  Backend API status: $BACKEND_STATUS"
          fi
